### ISSUE TITLE
npm run build failed with "Module not found"

### ISSUE THREAD

**Issue by SLAPaper** [7eu7d7/HCP-Diffusion-webui#1]
```
(sd_webui) slapaper@13900KS-4090:~/HCP-Diffusion-webui/web$ npm run build --verbose
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@9.6.7
npm info using node@v18.17.0
npm verb title npm run build
npm verb argv "run" "build" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/slapaper/.npm/_logs/2023-07-20T18_45_35_913Z-
npm verb logfile /home/slapaper/.npm/_logs/2023-07-20T18_45_35_913Z-debug-0.log

> view@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠸  Building for production...

 ERROR  Failed to compile with 1 error                                                            2:45:36 AM

 error

Module not found: Error: Can't resolve './src/main.js' in '/home/slapaper/HCP-Diffusion-webui/web'

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /home/slapaper/HCP-Diffusion-webui/web/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /home/slapaper/HCP-Diffusion-webui/web/node_modules/webpack/lib/webpack.js:148:8
    at /home/slapaper/HCP-Diffusion-webui/web/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/slapaper/HCP-Diffusion-webui/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/slapaper/HCP-Diffusion-webui/web/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/slapaper/HCP-Diffusion-webui/web/node_modules/webpack/lib/Cache.js:150:23)
    at /home/slapaper/HCP-Diffusion-webui/web/node_modules/webpack/lib/Compiler.js:1227:15
    at Hook.eval [as callAsync] (eval at create (/home/slapaper/HCP-Diffusion-webui/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/slapaper/HCP-Diffusion-webui/web/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/home/slapaper/HCP-Diffusion-webui/web/node_modules/webpack/lib/Compiler.js:1220:23)
npm verb exit 1
npm verb code 1
```

**Comment by IrisRainbowNeko** [comment]
bug fixed in new version
